# Generated by Django 2.2.16 on 2022-04-05 12:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20220405_1007'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folllow',
            new_name='Follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
    ]
